Slides for Langdev 2024
LionWeb-io/specification pull request #309
Opened 2024-10-19 16:07 UTC by enikao

2024-10-19 16:08 UTC, enikao commented
We should squash merge this PR, to minimize redundant binary data in the repo.

2024-10-21 07:22 UTC, enikao commented on resources/LangDev 2024 Talk-jos.pptx
@joswarmer I think we can delete this one?

2024-10-21 10:03 UTC, dslmeinte requested changes

2024-10-21 10:03 UTC, dslmeinte commented on resources/SEN-symposium-poster-layers.afpub
What format is this?

2024-10-21 10:03 UTC, dslmeinte commented on resources/LangDev 2024 Talk.pptx
Maybe we can go over all files in this directory and give them really descriptive file names? We've got a `LangDev talk.pptx` _and_ a `LangDev 2024 Talk.pptx` file now.

2024-11-05 16:10 UTC, merged